### ISSUE TITLE
Cambios sugeridos

### ISSUE THREAD

**Issue by TOTON95** [robotslatam/learning-path#2]
Hola, quiero proponer los siguientes cambios:

1. SPICE debe ser ubicado a la Simulacion de Circuitos 
2. Agregar Bluetooth y Bluetooth Low Energy a los sistemas de radio digital
3. Agregar Reinforcement Learning (aun no se su correcta traduccion) a la lista

Quedo atento a sus comentarios.

**Comment by diananerd** [comment]
Aceptado, se actualizarán estos cambios en el próximo PR.
